# Generated by Django 5.2.6 on 2025-10-01 13:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_name", models.CharField(max_length=255)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "extraction_temp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("extraction_time", models.IntegerField(blank=True, null=True)),
                ("cooking_overview", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ingredient",
            },
        ),
        migrations.CreateModel(
            name="Chemistry",
            fields=[
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="umami_api.ingredient",
                    ),
                ),
                ("glu", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("asp", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("imp", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("gmp", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ("amp", models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                (
                    "umami_aa",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "umami_nuc",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
                (
                    "umami_synergy",
                    models.DecimalField(decimal_places=3, default=0, max_digits=8),
                ),
            ],
            options={
                "db_table": "chemistry",
            },
        ),
        migrations.CreateModel(
            name="Flags",
            fields=[
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="umami_api.ingredient",
                    ),
                ),
                ("allergens", models.JSONField(blank=True, default=list)),
                ("dietary_restrictions", models.JSONField(blank=True, default=list)),
                ("umami_tags", models.JSONField(blank=True, default=list)),
                ("flavor_tags", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "flags",
            },
        ),
        migrations.CreateModel(
            name="TCM",
            fields=[
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="umami_api.ingredient",
                    ),
                ),
                (
                    "four_qi",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "five_flavors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "meridians",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
                ),
            ],
            options={
                "db_table": "tcm",
            },
        ),
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="umami_api.ingredient",
                    ),
                ),
            ],
            options={
                "db_table": "alias",
            },
        ),
    ]
