# Generated by Django 5.2.7 on 2025-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umami_api", "0002_trigram_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chemistry",
            name="umami_aa",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="chemistry",
            name="umami_nuc",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="chemistry",
            name="umami_synergy",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
